#!/bin/bash

# Send the header so that i3bar knows we want to use JSON:
echo '{"version":1,"click_events":true}'

# Begin the endless array.
echo '['

# We send an empty first array of blocks to make the loop simpler:
echo '[],'

# Now send blocks with information forever:

exec conky -c "$HOME/.conky/.conkyrc" &

PID=0

while read line; do
    if [ "$line" = "[" ]; then
        continue
    fi

    #line=$(echo "$line" | sed "s/^,//")
    line=${line/,/}
    name=$(echo "$line" | jshon -e name -u)
    x=$(echo "$line" | jshon -e x -u)

    if [ $PID -ne 0 ]; then
        kill $PID
        PID=0
        continue
    fi

    if [ "$name" = "todo" ]; then
        c=$(todo -c)
        offset=1700

        if [ "$x" -ge 1920 ]; then
            i3-nagbar -t warning -m "$line" &>/dev/null
            offset=3505
        fi

        todo | sed 's/^\(.*\)*$/%{c}\1%{c}/' | lemonbar -p -d -g 200x"$(echo "20 + 20*$c" | bc)+$offset"+21 & 
        PID=$!
    elif [ "$name" = "agenda" ]; then
        #txt=$(gcalcli agenda --nocolor)
        #c=$(echo "$txt" | wc -l)
        #echo "$txt" | lemonbar -f -p -d -g 400x$(echo "20 + 20*$c" | bc)+1500+21 & 
        #PID=$!
        chromium-browser --new-window 'https://calendar.google.com' &> /dev/null
    fi
done
