#!/bin/bash

# Send the header so that i3bar knows we want to use JSON:
echo '{"version":1,"click_events":true}'

# Begin the endless array.
echo '['

# We send an empty first array of blocks to make the loop simpler:
echo '[],'

# Now send blocks with information forever:

exec conky -c "$HOME/.conky/.conkyrc" &

PID=0

while read line; do
    if [ "$line" = "[" ]; then
        continue
    fi

    #line=$(echo "$line" | sed "s/^,//")
    line=${line/,/}
    name=$(echo "$line" | jshon -e name -u)
    x=$(echo "$line" | jshon -e x -u)

    if [ $PID -ne 0 ]; then
        killall lemonbar
        PID=0
        continue
    fi

    if [ "$name" = "todo" ]; then
        #c=$(todo -c)
        #offset=1700

        #i3-nagbar -t warning -m "$line" &>/dev/null
        if [ "$x" -ge $((1920-250)) -a "$x" -le 1920 ]; then
            x=$((1920-250))
        elif [ "$x" -ge $((2*1920-250)) ]; then
            x=$((2*1920-250))
        fi

        #todo | sed 's/^\(.*\)*$/%{c}\1%{c}/' | lemonbar -p -d -g 200x"$(echo "20 + 20*$c" | bc)+$offset"+21 & 
        #todo | sed 's/^\(.*\)*$/  \1/' | lemonbar -p -d -g 200x"$(echo "20 + 20*$c" | bc)+$offset"+21 & 
        #todo | paste -s -d'\n' - | lemonbar -p -d -g 200x"$(echo "20 + 20*$c" | bc)+$offset"+21 & 
        i=0
        todo | while read t; do
            #i3-nagbar -t warning -m "$t" &>/dev/null
            echo "  $t" | lemonbar -f "-misc-fixed-medium-r-normal--13-100-100-100-c-70-iso8859-1" -p -d -g "250x20+$x+$((20*i+20))" &
            i=$((i+1))
        done
        PID=1

    #elif [ "$name" = "agenda" ]; then
        #txt=$(gcalcli agenda --nocolor)
        #c=$(echo "$txt" | wc -l)
        #echo "$txt" | lemonbar -f -p -d -g 400x$(echo "20 + 20*$c" | bc)+1500+21 & 
        #PID=$!
        #chromium-browser --new-window 'https://calendar.google.com' &> /dev/null
    elif [ "$name" = "wifi" ]; then
        if [ "$x" -ge $((1920-250)) -a "$x" -le 1920 ]; then
            x=$((1920-250))
        elif [ "$x" -ge $((2*1920-250)) ]; then
            x=$((2*1920-250))
        fi

        iwconfig 2>/dev/null  | grep -o 'ESSID:".\+"' | sed 's/ESSID:"\(.\+\)"/  SSID: \1/' | lemonbar -f "-misc-fixed-medium-r-normal--13-100-100-100-c-70-iso8859-1" -p -d -g "200x20+$x+20" &
        (echo -n '  Remote: '; dig +short myip.opendns.com @resolver1.opendns.com) | lemonbar -f "-misc-fixed-medium-r-normal--13-100-100-100-c-70-iso8859-1" -p -d -g "200x20+$x+40" &
        ifconfig wlan0 | grep -o 'inet addr:\([0-9]\|\.\)\+' | grep -o '\([0-9]\|\.\)\+' | sed 's/^/  Local: /' | lemonbar -f "-misc-fixed-medium-r-normal--13-100-100-100-c-70-iso8859-1" -p -d -g "200x20+$x+60" &

        PID=1
    elif [ "$name" = "vpn_up" ]; then
        nmcli con down id sacooper.io &>/dev/null &
    elif [ "$name" = "vpn_down" ]; then
        nmcli con up id sacooper.io &>/dev/null 
    elif [ "$name" = "time" ]; then
        offset=350
        if [ "$x" -ge $((offset)) -a "$x" -le 1920 ]; then
            x=$((1920-offset))
        elif [ "$x" -ge $((2*1920-offset)) ]; then
            x=$((2*1920-offset))
        fi
        i=0;
        (grep -v '^$' /tmp/gcalcli_agenda.txt | sed 's/^\(... ... [[:digit:]]\+\)/\n%{+u}\1\n/' ) | tail -n+2| while read t; do
            echo "  $t" | lemonbar -f "-misc-fixed-medium-r-normal--13-100-100-100-c-70-iso8859-1" -p -d -g "$offset""x20+$x+$((20*i+20))" &
            i=$((i+1))
        done 
        PID=1
    fi
done
