#!/bin/bash

# Send the header so that i3bar knows we want to use JSON:
echo '{"version":1,"click_events":true}'

# Begin the endless array.
echo '['

# We send an empty first array of blocks to make the loop simpler:
echo '[],'

# Now send blocks with information forever:

exec conky -c "$HOME/.conky/.conkyrc" 2>/dev/null &

OPEN=0
LAST=""



TEXT='#c0c5ce'
BG='#2b303b'
GREEN='#a3be8c'
RED='#bf616a'
LEMONCMD="lemonbar -f -misc-fixed-medium-r-normal--13-100-100-100-c-70-iso8859-1 -p -d -F $TEXT -B $BG"


offset() {
    x="$1"
    w="$2"
    if [ "$x" -ge $((1920-w)) -a "$x" -le 1920 ]; then
        echo $((1920-w))
    elif [ "$x" -ge $((2*1920-w)) ]; then
        echo $((2*1920-w))
    else
        echo "$x"
    fi
}

while read line; do
    if [ "$line" = "[" ]; then
        continue
    fi

    #if [ "$(xrandr | grep 'HDMI1 connected')" -gt 0 ]; then
        #xrandr --output HDMI1 --off
    #else 
        #xrandr --output HDMI1 --auto --left-of eDP1
    #fi
    #line=$(echo "$line" | sed "s/^,//")
    line=${line/,/}
    name=$(echo "$line" | jshon -e name -u)
    x=$(echo "$line" | jshon -e x -u)

    if [ $OPEN -ne 0 ]; then
        killall lemonbar
        OPEN=0

        if [ "$name" = "$LAST" ]; then
            continue
        fi
    fi

    if [ "$name" = "todo" ]; then
        #c=$(todo -c)
        #offset=1700
        w=350

        x=$(offset "$x" "$w")
        x=$((x-w/2))

        #i3-nagbar -t warning -m "$line" &>/dev/null

        i=0
        todo -b | while read t; do
            echo "  $t" | $LEMONCMD -g "$w""x20+$x+$((20*i+20))" &
            i=$((i+1))
        done
        OPEN=1
    elif [ "$name" = "wifi" ]; then
        w=250
        x=$(offset "$x" "$w")
        x=$((x - w/2))

        #iwconfig 2>/dev/null  | grep -o 'ESSID:".\+"' | sed 's/ESSID:"\(.\+\)"/  SSID: \1/' | lemonbar -f "-misc-fixed-medium-r-normal--13-100-100-100-c-70-iso8859-1" -p -d -g "$w""x20+$x+20" &
        #(echo -n '  Remote: '; dig +short myip.opendns.com @resolver1.opendns.com) | lemonbar -f "-misc-fixed-medium-r-normal--13-100-100-100-c-70-iso8859-1" -p -d -g "$w""x20+$x+40" &
        #ifconfig wlan0 | grep -o 'inet addr:\([0-9]\|\.\)\+' | grep -o '\([0-9]\|\.\)\+' | sed 's/^/  Local: /' | lemonbar -f "-misc-fixed-medium-r-normal--13-100-100-100-c-70-iso8859-1" -p -d -g "$w""x20+$x+60" &
        iwconfig 2>/dev/null  | grep -o 'ESSID:".\+"' | sed 's/ESSID:"\(.\+\)"/  SSID: \1/' | $LEMONCMD -g "$w""x20+$x+20" &
        (echo -n '  Remote: '; dig +short myip.opendns.com @resolver1.opendns.com) | $LEMONCMD -g "$w""x20+$x+40" &
        ifconfig wlan0 | grep -o 'inet addr:\([0-9]\|\.\)\+' | grep -o '\([0-9]\|\.\)\+' | sed 's/^/  Local: /' | $LEMONCMD -g "$w""x20+$x+60" &

        OPEN=1
    elif [ "$name" = "vpn_up" ]; then
        nmcli con down id sacooper.io &>/dev/null &
    elif [ "$name" = "vpn_down" ]; then
        nmcli con up id sacooper.io &>/dev/null 
    elif [ "$name" = "time" ]; then
        w=350
        x=$(offset "$x" "$w")
        i=0;
        (grep -v '^$' /tmp/gcalcli_agenda.txt | sed 's/^\(... ... [[:digit:]]\+\)/\n%{+u}\1\n/' ) | tail -n+2| while read t; do
            echo "  $t" | $LEMONCMD -g "$w""x20+$x+$((20*i+20))" &
            i=$((i+1))
        done 
        OPEN=1
    elif [ "$name" = "cpu" ]; then
        w=250
        x=$(offset "$x" "$w")
        x=$((x-w/3))
        i=1;
        printf "%7s %-5s %s" "PID:" "CPU" "COMMAND" | $LEMONCMD -g "$w""x20+$x+20" &
        ps -axo pid,%cpu,comm | tail -n+2 | sort -r -nk2 | head -n10 | tr -s ' ' | sed 's/^ *//' | while read t; do
            a="$(echo "$t" | cut -f1 -d' ')"
            b="$(echo "$t" | cut -f2 -d' ')"
            c="$(echo "$t" | cut -f3 -d' ')"
            printf "%7s %-5s %s" "$a:" "$b" "$c" | $LEMONCMD -g "$w""x20+$x+$((20*i+20))" &
            #echo "  $t" | lemonbar -f "-misc-fixed-medium-r-normal--13-100-100-100-c-70-iso8859-1" -p -d -g "$w""x20+$x+$((20*i+20))" &
            i=$((i+1))
        done
        OPEN=1
    elif [ "$name" = "mem" ]; then
        w=250
        x=$(offset "$x" "$w")
        x=$((x-w/3))
        i=1;
        printf "%7s %-5s %s" "PID:" "MEM" "COMMAND" | $LEMONCMD -g "$w""x20+$x+20" &

        ps -axo pid,%mem,comm | tail -n+2 | sort -r -nk2 | head -n10 | tr -s ' ' | sed 's/^ *//' | while read t; do
            a="$(echo "$t" | cut -f1 -d' ')"
            b="$(echo "$t" | cut -f2 -d' ')"
            c="$(echo "$t" | cut -f3 -d' ')"
            printf "%7s %-5s %s" "$a:" "$b" "$c" | $LEMONCMD -g "$w""x20+$x+$((20*i+20))" &
            i=$((i+1))
        done
        OPEN=1
    elif [ "$name" = "volume" ]; then 
        button=$(echo "$line" | jshon -e button -u)
        if [ "$button" = "1" ]; then
            amixer -D pulse sset Master 5%+ &>/dev/null
        elif [ "$button" = "3" ]; then
            amixer -D pulse sset Master 5%- &>/dev/null
        fi
    elif [ "$name" = "music" ]; then
        button=$(echo "$line" | jshon -e button -u)
        if [ "$button" = "1" ]; then
            mocp -G &>/dev/null
        elif [ "$button" = "3" ]; then
            mocp --next &>/dev/null
        fi
    elif [ "$name" = "updates" ]; then
        terminator --command='echo "Updating"; sudo apt-get update && sudo apt-get upgrade && rm /tmp/ubuntu_updates.txt' &>/dev/null & disown
    elif [ "$name" = "weather" ]; then
        w=300
        x=$(offset "$x" "$w")
        x=$((x-w/3))
        i=0
        tail -n+2 /tmp/weather.txt | while read line; do
            echo "  $line" | $LEMONCMD -g "$w""x20+$x+$((20*i+20))" &
            i=$((i+1))
        done
        OPEN=1
    elif [ "$name" = "mail" ]; then
        button=$(echo "$line" | jshon -e button -u)
        if [ "$button" = "1" ]; then
            max=$(for x in "$HOME/Mail/"*; do echo "$(basename $x)" | wc -c; done | sort -rn | head -n1)
            max=$((max+4))
            w=$((max*2*5))
            x=$(offset "$x" "$w")
            x=$((x-w/3))
            i=0
            for acct in "$HOME/Mail/"*; do
                c=$(find "$acct/INBOX/new" -type f | wc -l)
                l=$(basename "$acct")
                #echo "  $l:$c" | lemonbar -f "-misc-fixed-medium-r-normal--13-100-100-100-c-70-iso8859-1" -p -d -g "$w""x20+$x+$((20*i+20))" &
                printf "  %-""$max""s%s" "$l:" "$c" | $LEMONCMD -g "$w""x20+$x+$((20*i+20))" &
                i=$((i+1))
            done
            OPEN=1
        elif [ "$button" = "3" ]; then
            pkill offlineimap --signal SIGUSR1
        fi
    fi

    if [ "$OPEN" -eq 1 ]; then
        LAST="$name"
    fi
done
